### ISSUE TITLE
Backup folder...

### ISSUE THREAD

**Issue by danihenrique** [XiaocongDong/mongodb-backup-manager#4]
Hello!

Nice job! Very clean and easy to management all the backups.

I must know, where the  files are storaged ?

I coudn't find it...

Thx

**Comment by XiaocongDong** [comment]
Thanks for your appreciation!

What kind of files are you looking for? The backup configurations and the data backed up from your MongoDBs should be located in the DB you configure, take a look at Notes section of the [ReadMe.md](https://github.com/XiaocongDong/mongodb-backup-manager/blob/master/README.md)
