### ISSUE TITLE
Few Issues

### ISSUE THREAD

**Issue by xtechgamer735** [XiaocongDong/mongodb-backup-manager#5]
Hey! Love the ethos of this project but having a few problems getting it to work.

Firstly, I couldn't install from repo. It gives a 404 but was able to do it via a git clone so no worries there. This might throw a few people who might not have NPM experience.

The second problem I am having is actually starting a backup. Whenever I try to run it, I get the following error

`Backup <my backup> failed for Cannot read property 'toLocaleString' of null`

Would you be able to help fix this? There are no error logs produced I am afraid.

Thanks!

**Comment by XiaocongDong** [comment]
Thanks for using this project!

Sorry I could not do the dubugging with this short error message, could you provide more details about this? Like How did you get this error? 

Thanks!

**Comment by xtechgamer735** [comment]
Hello! This is displayed in the notifications section of the backup area, I have attached a screen shot. It occurs if I try to manually backup or if it does it automatically.
![screen shot 2018-04-29 at 14 24 58](https://user-images.githubusercontent.com/5082164/39407120-26c13346-4bb9-11e8-982a-116147b2e71d.png)

Thanks :)

**Comment by XiaocongDong** [comment]
Can I take a look at your backup configuration for this SubZeroNetwork database?

**Comment by xtechgamer735** [comment]
Yeah sure, am I able to PM you as it’s got sensitive data on?

Thanks :)

**Comment by XiaocongDong** [comment]
You can blur all the sensitive data like the db name and authDB and then show me the screenshot of the configuration..

**Comment by xtechgamer735** [comment]
![screen shot 2018-04-30 at 11 22 50](https://user-images.githubusercontent.com/5082164/39423247-d4e496a2-4c68-11e8-821b-e7a24c1738b3.png)

Sure - thanks. The credentials I'm using work 100% as ive tested them with adminMongo.

**Comment by XiaocongDong** [comment]
Sorry for replying so late, I was too busy last week to fix this bug, now this bug has been fixed by this commit https://github.com/XiaocongDong/mongodb-backup-manager/commit/25fd775fbfa392d32a45c5e8ec8aa793b3db93ba

cheers

**Comment by xtechgamer735** [comment]
Nice one thank you! I’ll give it a go tomorrow and report back my findings :)
