### ISSUE TITLE
How to change the storage location of backup?

### ISSUE THREAD

**Issue by kaliiosto** [XiaocongDong/mongodb-backup-manager#8]

**Comment by XiaocongDong** [comment]
Thanks for using mongodb-backup-manager!

The database used to store all of the backup should be set when you start the system, so if you want to change the location of backup, you will need to restart the system. FYI: [https://xiaocongdong.github.io/mongodb-backup-manager/#/docs?tab=setup](https://xiaocongdong.github.io/mongodb-backup-manager/#/docs?tab=setup)
